package client.controller.constant;

import client.view.soundManager.SoundPlayer;

import javax.swing.*;
import java.awt.*;


public class Constants {
    public static final String SERVER_ADDRESS = "localhost";
    public static final int TCP_PORT = 1234;
    public static final Dimension GLASS_FRAME_DIMENSION = Toolkit.getDefaultToolkit().getScreenSize();
    public static final Dimension GAME_PANEL_INITIAL_DIMENSION = new Dimension(700, 700);
    public static final int FPS = GraphicsEnvironment.getLocalGraphicsEnvironment().getScreenDevices()[0].getDisplayMode().getRefreshRate();
    public static final double FRAME_UPDATE_TIME=(double) 1000/FPS;
    public static final int UPS = 100;
    public static final double MODEL_UPDATE_TIME=(double) 1000/UPS;
    public static final double EPSILON_RADIUS = 25;
    public static final Dimension SIDE_PANELS_DIMENSION = new Dimension(850, 850);
    public static final double SHRINK_DECELERATION = 75;
    public static final Dimension GAME_PANEL_END_SIZE = new Dimension(15, 15);
    public static final Dimension GAME_PANEL_MIN_DIMENSION = new Dimension(300, 300);
    public static final Dimension GAME_PANEL_START_DIMENSION_ERROR = new Dimension(430, 430);
    public static int BULLET_REDUCE_HP = 5;
    public static int HOT_BULLET_REDUCE_HP = 50;
    public static int EPSILON_REDUCE_HP = 10;
    public static int INITIAL_XP = 0;
    public static double CHECKPOINT_SIZE = 45;
    public static int INITIAL_HP = 100;
    public static int SKILL_TREE_ASTRAPE_DAMAGE = 2;
    public static int SKILL_TREE_CERBERUS_DAMAGE = 10;
    public static int SKILL_TREE_CHIRON_ADD_HP = 3;
    public static final Dimension GAME_PANEL_START_DIMENSION = new Dimension(400, 400);
    public static final int TRIANGLE_ENEMY_HP = 15;
    public static final int TRIANGLE_ENEMY_REDUCER_HP = 10;
    public static final int TRIANGLE_ENEMY_COLLECTIBLE_NUMBER = 2;
    public static final int TRIANGLE_ENEMY_COLLECTIBLE_XP = 5;
    public static final int SQUARE_ENEMY_HP = 10;
    public static final int SQUARE_ENEMY_REDUCER_HP = 6;
    public static final int SQUARE_ENEMY_COLLECTIBLE_NUMBER = 1;
    public static final int SQUARE_ENEMY_COLLECTIBLE_XP = 5;
    public static final int BARRICADOS_ENEMY_HP = Integer.MAX_VALUE;
    public static final int BARRICADOS_ENEMY_REDUCER_HP = 0;
    public static final int BARRICADOS_ENEMY_COLLECTIBLE_NUMBER = 0;
    public static final int BARRICADOS_ENEMY_COLLECTIBLE_XP = 0;
    public static final int ORB_ENEMY_HP = 30;
    public static final int ORB_ENEMY_REDUCER_HP = 0;
    public static final int ORB_ENEMY_LASER_REDUCER_HP = 12;
    public static final int ORB_ENEMY_COLLECTIBLE_NUMBER = 1;
    public static final int ORB_ENEMY_COLLECTIBLE_XP = 30;
    public static final int OMENOCT_ENEMY_HP = 20;
    public static final int OMENOCT_ENEMY_REDUCER_HP = 8;
    public static final int OMENOCT_ENEMY_COLLECTIBLE_NUMBER = 8;
    public static final int OMENOCT_ENEMY_COLLECTIBLE_XP = 4;
    public static final int WYRM_ENEMY_HP = 12;
    public static final int WYRM_ENEMY_REDUCER_HP = 0;
    public static final int WYRM_ENEMY_RANGED_REDUCER_HP = 8;
    public static final int WYRM_ENEMY_COLLECTIBLE_NUMBER = 2;
    public static final int WYRM_ENEMY_COLLECTIBLE_XP = 8;
    public static final int ARCHMIRE_ENEMY_HP = 30;
    public static final int ARCHMIRE_ENEMY_REDUCER_HP = 0;
    public static final int ARCHMIRE_ENEMY_COLLECTIBLE_NUMBER = 5;
    public static final int ARCHMIRE_ENEMY_COLLECTIBLE_XP = 6;
    public static final int ARCHMIRE_ENEMY_DROWN_REDUCER_HP = 10;
    public static final int ARCHMIRE_ENEMY_AOE_REDUCER_HP = 2;
    public static final int NECROPICK_ENEMY_HP = 10;
    public static final int NECROPICK_ENEMY_REDUCER_HP = 0;
    public static final int NECROPICK_ENEMY_COLLECTIBLE_NUMBER = 4;
    public static final int NECROPICK_ENEMY_COLLECTIBLE_XP = 2;
    public static final double NECROPICK_EPSILON_MIN_DISTANCE = 5 * EPSILON_RADIUS;
    public static final double WYRM_EPSILON_MIN_DISTANCE = 10 * EPSILON_RADIUS;
    public static final int NECROPICK_RANGE_ATTACK_REDUCE_HP = 5;
    public static final int BOSS_RAPID_FIRE_ATTACK_REDUCE_HP = 10;
    public static final int NECROPICK_RANGE_ATTACK_NUMBER = 8;
    public static final int BOSS_RAPID_FIRE_ATTACK_NUMBER = 10;
    public static final int COLLECTIBLE_EXISTENCE = 4000;
    public static final int COLLECTIBLE_SIZE = 10;
    public static final int IMPACT_RADIUS = 250;
    public static final double ENEMY_SPEED_EASY_LEVEL = 1;
    public static final double ENEMY_SIZE_EASY_LEVEL = 60;
    public static final int END_SECOND_SPAWN_KILLED_EASY = 4;
    public static final int END_SECOND_SPAWN_KILLED_MEDIUM = 6;
    public static final int END_SECOND_SPAWN_KILLED_HARD = 8;
    public static final Color SHOW_COLOR = new Color(28, 112, 49);
    public static final Image BACKGROUND_IMAGE = new ImageIcon("resources/Background3.jpg").getImage();
    public static double EPSILON_SPEED = 5.5;
    public static double ACCELERATION_ADD_VALUE = 0.1;
    public static double ACCELERATION_MAX_VAL = 0.8;
    public static double ERROR = 5;
    public static int OMENOCT_BULLET_REDUCE_HP = 4;
    public static int BOSS_HEAD_HP = 300;
    public static int BOSS_HAND_HP = 100;
    public static double BOSS_SIZE = 200;
    public static int BOSS_REDUCE_HP = 10;
    public static double BOSS_AOE_RADIUS = 30;
    public static int BOSS_AOE_REDUCE_HP = 10;
    public static int BOSS_AOE_CENTER_NUMBERS = 3;
    public static int BOSS_BULLET_REDUCE_HP = 10;
    public static int BOSS_ADDED_XP = 250;
    public static SoundPlayer bulletSound = new SoundPlayer("resources/songs/BulletSound.wav");
    public static SoundPlayer startWave = new SoundPlayer("resources/songs/statrtWave.wav");
    public static SoundPlayer gameOver = new SoundPlayer("resources/songs/GameOver.wav");
    public static SoundPlayer winGame = new SoundPlayer("resources/songs/WinGame.wav");
    public static SoundPlayer injured = new SoundPlayer("resources/songs/injured.wav");
    public static SoundPlayer enemyDeath = new SoundPlayer("resources/songs/enemyDeath.wav");
    public static SoundPlayer addCollectible = new SoundPlayer("resources/songs/addCollectible.wav");
}
